### ISSUE TITLE
Game Ideas

### ISSUE THREAD

**Issue by ailox** [xHain-hackspace/PlotterFeeder#1]
Brainstorming w/ @NameNotReturned 
* Snake?
* Darts?
* Nethack-style maze adventure (with endless paper?)
* Text adventure
* Understand morse code from key?
* Tic-tac-toe (boooring)
* Chat (with multiple plotters)
* Signature copy as-a-service (signature vector from tablet? From raster graphic?)
* Selfie booth
* Guess a picture game (with buzzer button)

**Comment by arglurgl** [comment]
Closing this for cleanup. It's not really an open issue and we'll still have it archived in the closed issues. :)
